title: Sriram Sankar
baseURL: /
taxonomies:
  category: "categories"
  tag: "tags"
disableKinds:
  - RSS
markup:
  goldmark:
    renderer:
      unsafe: true
permalinks:
    categories: "/:slug/"
Params:
  social:
    share:
      facebook: true
      linkedin: true
      twitter: true
      whatsapp: false
      email: true
