backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://spectram.netlify.app
logo_url: https://spectram.netlify.app/static/images/srs-logo-black.svg

collections:
  - name: "thoughts"
    label: "thoughts"
    slug: "{{slug}}" #This slug variable is different from that of preview_path
    preview_path: "blog/{{year}}/{{month}}/{{slug}}"
    folder: "content/thoughts"
    identifier_field: title
    create: true
    extension: md
    file: "content/thoughts/.md"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "subtitle", name: "subtitle", widget: "string", required: false,}
      - { label: "excerpt", name: "excerpt", widget: "string" , required: false,}
      - { label: "categories", name: "categories", widget: "string", required: false,}
      - { label: "tags", name: "tags", widget: "string", required: false,}
      - { label: "datetime", name: "datetime", widget: "datetime",date_format: "YYYY-MM-DD",required: false, }
      - { widget: "string", name: "slug", label: "slug", required: true, pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$','A slug can have no spaces or special characters']}
      - { label: "thumb_img_path", name: "thumb_img_path", widget: "image" }
      - { label: "content_img_path", name: "content_img_path", widget: "image" }
      - { label: "thumb_img_alt", name: "thumb_img_alt", widget: "string" }
      - { label: "hide_header", name: "hide_header", widget: "boolean", default: false, required: false, }
      - { label: "layout", name: "layout", widget: "string",default: "post"}
      - { label: "body", name: "body", widget: "markdown" }
      
      - label: "seo"        #Add Open Graph options later
        name: "seo"
        widget: "object"
        fields:
        - { label: "Focus Keyword", name: "yoast_keyword", widget: "string",required: false, }
        - { label: "SEO Meta Description", name: "description", widget: "string",required: false, }
        - { label: "SEO Meta Title", name: "metatitle", widget: "string", required: false,}
        - { label: "Social Image", name: "socialImage", widget: "image", required: false,}

  - name: "sideprojects" 
    label: "sideprojects"
    slug: "{{slug}}"
    extension: md
    preview_path: "blog/{{year}}/{{month}}/{{slug}}"
    folder: "content/sideprojects"
    identifier_field: title
    create: true
    file: "content/sideprojects/.md"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "subtitle", name: "subtitle", widget: "string",required: false, }
      - { label: "excerpt", name: "excerpt", widget: "string", required: false, }
      - { label: "categories", name: "categories", widget: "string", required: false,}
      - { label: "tags", name: "tags", widget: "string", required: false,}
      - { label: "datetime", name: "datetime", widget: "datetime",date_format: "YYYY-MM-DD",required: false, }
      - { widget: "string", name: "slug", label: "slug", required: true, pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$','A slug can have no spaces or special characters']}
      - { label: "thumb_img_path", name: "thumb_img_path", widget: "image" }
      - { label: "content_img_path", name: "content_img_path", widget: "image" }
      - { label: "thumb_img_alt", name: "thumb_img_alt", widget: "string" }
      - { label: "hide_header", name: "hide_header", widget: "boolean", default: false, required: false,}
      - { label: "layout", name: "layout", widget: "string", default: "post"}
      - { label: "body", name: "body", widget: "markdown" }
      - label: "seo"
        name: "seo"
        widget: "object"
        fields:
        - { label: "Focus Keyword", name: "yoast_keyword", widget: "string",required: false, }
        - { label: "SEO Meta Description", name: "description", widget: "string",required: false, }
        - { label: "SEO Meta Title", name: "metatitle", widget: "string", required: false,}
        - { label: "Social Image", name: "socialImage", widget: "image", required: false,}

